language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"

env:
  - DJANGO="Django>=1.8,<1.9"
  - DJANGO="Django>=1.9,<1.10"
  - DJANGO="Django>=1.10,<1.11"

install:
  - python setup.py install
  - pip install $DJANGO
  - pip install psycopg2

script:
  - createdb facebook_auth-test-database
  - python runtests.py
