language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"

env:
  - DJANGO="Django>=1.6,<1.7"
  - DJANGO="Django>=1.5,<1.6"

install:
  - python setup.py install
  - pip install $DJANGO
  - pip install psycopg2

script:
  - createdb facebook_auth-test-database
  - python runtests.py
